name: DiscordRelay
author: lukeeey
description: Relay chat between Discord and a Minecraft server
version: ${project.version}
api: [1.0.5]
main: io.github.lukeeey.discordrelay.nukkit.DiscordRelayPlugin
website: https://github.com/lukeeey/DiscordRelay
commands:
  discordrelay:
    aliases: [drelay]
    usage: /drelay reload
    permission: drelay.reload
  discord:
    description: Display Discord server link
permissions:
  drelay.reload:
    description: Allows the player to reload the config
    default: op