name: DiscordRelay
author: lukeeey
description: Relay chat between Discord and a Minecraft server
version: ${project.version}
api: [1.0.5]
main: io.github.lukeeey.discordrelay.nukkit.DiscordRelayPlugin
website: https://github.com/lukeeey/DiscordRelay
commands:
  discord:
    description: Display Discord server link