name: DiscordRelay
author: lukeeey
description: Relay chat between Discord and a Minecraft server
version: ${project.version}
api: [1.0.5]
main: dev.lukeeey.discordrelay.nukkit.DiscordRelayNukkit
website: https://github.com/lukeeey/DiscordRelay
commands:
  discordrelay:
    aliases: [drelay]
    usage: /drelay [reload|restart]
  discord:
    description: Display Discord server link
permissions:
  drelay.allowrolepings:
    default: op
  drelay.reload:
    default: op
  drelay.restart:
    default: op
  drelay.sendtodiscord:
    default: true
  drelay.receivefromdiscord:
    default: true