name: DiscordRelay
author: lukeeey
description: Relay chat between Discord and a Minecraft server
version: ${project.version}
api-version: 1.13
main: io.github.lukeeey.discordrelay.bukkit.DiscordRelayPlugin
softdepend: [PlaceholderAPI]
website: https://github.com/lukeeey/DiscordRelay
commands:
  discordrelay:
    aliases: [drelay]
    usage: /drelay reload
    permission: drelay.reload
  discord:
    description: Display Discord server link
permissions:
  drelay.reload: op